import os

from dotenv import load_dotenv

load_dotenv(override=True)

__all__ = [
    "DEEPSEEK_API_KEY", "DEEPSEEK_API_URL",
    "DASHSCOPE_API_KEY", "DASHSCOPE_API_URL",
    "ZHIPUAI_API_KEY", "ZHIPUAI_API_URL",
    "QIANFAN_ACCESS_KEY", "QIANFAN_SECRET_KEY",
    "LANGSMITH_API_KEY", "AMAP_API_KEY",
    "UNSPLASH_ACCESS_KEY", "UNSPLASH_SECRET_KEY",
]

DEEPSEEK_API_KEY=os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_API_URL=os.getenv("DEEPSEEK_API_URL")

DASHSCOPE_API_KEY=os.getenv("DASHSCOPE_API_KEY")
DASHSCOPE_API_URL=os.getenv("DASHSCOPE_API_URL")

ZHIPUAI_API_KEY=os.getenv("ZHIPUAI_API_KEY")
ZHIPUAI_API_URL=os.getenv("ZHIPUAI_API_URL")

QIANFAN_ACCESS_KEY=os.getenv("QIANFAN_ACCESS_KEY")
QIANFAN_SECRET_KEY=os.getenv("QIANFAN_SECRET_KEY")

LANGSMITH_API_KEY=os.getenv("LANGSMITH_API_KEY")

AMAP_API_KEY=os.getenv("AMAP_API_KEY")

UNSPLASH_ACCESS_KEY=os.getenv("UNSPLASH_ACCESS_KEY")
UNSPLASH_SECRET_KEY=os.getenv("UNSPLASH_SECRET_KEY")

